=== tadmacy/Cerebro-beta/greek_words.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by Tad Macy (private) -->
<!--DTD generated by XMLSPY v2004 rel. 3 U (http://www.xmlspy.com)-->
<!ELEMENT card (side+)>
<!ELEMENT cards (card+)>
<!ELEMENT side (#PCDATA)>
<!ATTLIST side
  x:str CDATA #IMPLIED
>

=== tadmacy/Cerebro-beta/v1-greek_words.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cards SYSTEM "greek_words.dtd">
<cards>
<!--   <card>
    <side><![CDATA[0123456 789 0123456 789]]></side>
    <side><![CDATA[0123456 789012345 6789 2345 678]]></side>
    <side><![CDATA[side 3]]></side>
  </card>
  <card>
    <side><![CDATA[0123456 789 0123456 78901234 56 789 0123456 789]]></side>
    <side><![CDATA[012 3456789012 3456789]]></side>
    <side><![CDATA[to side 3]]></side>
  </card>-->
  <card>
    <side><![CDATA[ἀγαθός -ή - όν]]></side>
    <side><![CDATA[good]]></side>
  </card>
  <card>
    <side><![CDATA[ἀγγέλω]]></side>
    <side><![CDATA[ἀγγελῶ, ἤγγειλα, ἤγγελκα, ἤγγελμαι, ἠγγέλθην]]></side>
    <side><![CDATA[to announce, tell]]></side>
  </card>
  <card>
    <side><![CDATA[ἄγγελος]]></side>
    <side><![CDATA[ἀγγέλου, ὁ]]></side>
    <side><![CDATA[messenger]]></side>
  </card>
  <card>
    <side><![CDATA[ἀγορἀ]]></side>
    <side><![CDATA[ἀγορᾶς, ἡ]]></side>
    <side><![CDATA[marketplace, citycenter]]></side>
  </card>
  <card>
    <side><![CDATA[ἀγνοέω]]></side>
    <side><![CDATA[ἀγνοήσω, ἠγνόησα, ἠγνόηκα, ἠγνόημαι, ἠγνοήθην]]></side>
    <side><![CDATA[to not know, be unaware]]></side>
  </card>
  <card>
    <side><![CDATA[ἄγω]]></side>
    <side><![CDATA[ἄξω, ἤγαγον, ἦχα, ἦγμαι, ἦχθην]]></side>
    <side><![CDATA[to lead, drive, do]]></side>
  </card>
  <card>
    <side><![CDATA[ἀγών]]></side>
    <side><![CDATA[ἀγῶνος, ὁ]]></side>
    <side><![CDATA[struggle, contest, game]]></side>
  </card>
  <card>
    <side><![CDATA[ἀδελφός]]></side>
    <side><![CDATA[ἀδελφοῦ, ὁ]]></side>
    <side><![CDATA[brother]]></side>
  </card>
  <card>
    <side><![CDATA[ἀδικέω]]></side>
    <side><![CDATA[ἀδικήσω, ἠδίκησα, ἠδίκηκα, ἠδίκημαι, ἠδικήθην]]></side>
    <side><![CDATA[to do wrong, be just]]></side>
  </card>
  <card>
    <side><![CDATA[ἄδικος -η -ον]]></side>
    <side><![CDATA[unjust]]></side>
  </card>
  <card>
    <side><![CDATA[ἀδύνατος -ον]]></side>
    <side><![CDATA[impossible, incapable]]></side>
  </card>
  <card>
    <side><![CDATA[ἀεί/αἰεί]]></side>
    <side><![CDATA[always]]></side>
  </card>
  <card>
    <side><![CDATA[ἀθάνατος -ον]]></side>
    <side><![CDATA[immortal]]></side>
  </card>
  <card>
    <side><![CDATA[᾽Αθήναζε]]></side>
    <side><![CDATA[to Athens]]></side>
  </card>
  <card>
    <side><![CDATA[᾽Αθῆναι]]></side>
    <side><![CDATA[᾽Αθηνῶν, αἱ]]></side>
    <side><![CDATA[Athens]]></side>
  </card>
  <card>
    <side><![CDATA[᾽Αθήνασι]]></side>
    <side><![CDATA[at Athens]]></side>
  </card>
  <card>
    <side><![CDATA[ἐν ταῖς ᾽Αθήναις]]></side>
    <side><![CDATA[in Athens]]></side>
  </card>
  <card>
    <side><![CDATA[᾽Αθηνᾶ]]></side>
    <side><![CDATA[᾽Αθηνᾶς, ἡ]]></side>
    <side><![CDATA[Athena]]></side>
  </card>
  <card>
    <side><![CDATA[ἀθυμία]]></side>
    <side><![CDATA[ἀθυμίας, ἡ]]></side>
    <side><![CDATA[despair, lack of spirit]]></side>
  </card>
  <card>
    <side><![CDATA[ἄθυμος -ον]]></side>
    <side><![CDATA[disheartened]]></side>
  </card>
  <card>
    <side><![CDATA[αἱρέω]]></side>
    <side><![CDATA[αἱρήσω, εἷλον, ᾕρηκα, ᾕρημαι, ᾑρέθην]]></side>
    <side><![CDATA[(act) seize; (mid) choose]]></side>
  </card>
  <card>
    <side><![CDATA[ἀδικία]]></side>
    <side><![CDATA[ἀδικίας, ἡ]]></side>
    <side><![CDATA[injustice]]></side>
  </card>
  <card>
    <side><![CDATA[αἰσθάνομαι]]></side>
    <side><![CDATA[αἰσθήσομαι, ᾐσθόμην, ᾔσθημαι]]></side>
    <side><![CDATA[to perceive, feel]]></side>
  </card>
  <card>
    <side><![CDATA[αἰσχρός -α -ον]]></side>
    <side><![CDATA[shameful]]></side>
  </card>
  <card>
    <side><![CDATA[αἰσχύνη]]></side>
    <side><![CDATA[αἰσχύνης, ἡ]]></side>
    <side><![CDATA[shame, dishonor]]></side>
  </card>
  <card>
    <side><![CDATA[αἰτέω]]></side>
    <side><![CDATA[αἰτήσω, ᾔτησα, ᾔτηκα, ᾔτημαι, ᾐτήθην]]></side>
    <side><![CDATA[to ask for, demand]]></side>
  </card>
  <card>
    <side><![CDATA[αἰτία]]></side>
    <side><![CDATA[αἰτίας, ἡ]]></side>
    <side><![CDATA[cause, reason, blame, responsibility]]></side>
  </card>
  <card>
    <side><![CDATA[αἴτιος -α -ον]]></side>
    <side><![CDATA[responsible for, to blame for]]></side>
  </card>
  <card>
    <side><![CDATA[ἀκούω]]></side>
    <side><![CDATA[ἀκούσομαι, ἤκουσα, ἀκήκοα, ἤκουσμαι, ἠκούσθην]]></side>
    <side><![CDATA[to hear, listen to]]></side>
  </card>
  <card>
    <side><![CDATA[ἀκρόπολις]]></side>
    <side><![CDATA[ἀκροπόλεως, ἡ]]></side>
    <side><![CDATA[citadel, uppercity, Acropolis]]></side>
  </card>
  <card>
    <side><![CDATA[ἄκρος -α -ον]]></side>
    <side><![CDATA[top most, high]]></side>
  </card>
  <card>
    <side><![CDATA[ἀλήθεια]]></side>
    <side><![CDATA[ἀληθείας, ἡ]]></side>
    <side><![CDATA[truth]]></side>
  </card>
  <card>
    <side><![CDATA[ἀληθής -ές]]></side>
    <side><![CDATA[1]]></side>
  </card>
  <card>
    <side><![CDATA[ἀλλά]]></side>
    <side><![CDATA[but]]></side>
  </card>
  <card>
    <side><![CDATA[ἀλλήλους -ας -α]]></side>
    <side><![CDATA[each other]]></side>
  </card>
  <card>
    <side><![CDATA[ἄλλοθεν]]></side>
    <side><![CDATA[from elsewhere]]></side>
  </card>
  <card>
    <side><![CDATA[ἄλλοθι]]></side>
    <side><![CDATA[elsewhere]]></side>
  </card>
  <card>
    <side><![CDATA[ἄλλος -η -ον]]></side>
    <side><![CDATA[other, another, the rest]]></side>
  </card>
  <card>
    <side><![CDATA[ἄλλοσε]]></side>
    <side><![CDATA[to elsewhere]]></side>
  </card>
  <card>
    <side><![CDATA[ἄλλοτε]]></side>
    <side><![CDATA[at another time]]></side>
  </card>
  <card>
    <side><![CDATA[ἅμα]]></side>
    <side><![CDATA[at the same time]]></side>
  </card>
  <card>
    <side><![CDATA[ἁμαρτάνω]]></side>
    <side><![CDATA[ἁμαρτήσομαι, ἥμαρτον, ἡμάρτηκα, ἡμάρτημαι, ἡμαρτήθην]]></side>
    <side><![CDATA[to miss, make a mistake, sin]]></side>
  </card>
  <card>
    <side><![CDATA[ἀμφί]]></side>
    <side><![CDATA[(gen) about; (dat) around; (acc) around]]></side>
  </card>
  <card>
    <side><![CDATA[ἀμφότερος -α -ον]]></side>
    <side><![CDATA[both]]></side>
  </card>
  <card>
    <side><![CDATA[ἄν]]></side>
    <side><![CDATA[modal particle]]></side>
  </card>
  <card>
    <side><![CDATA[ἀνά]]></side>
    <side><![CDATA[(acc) up; (through) through out]]></side>
  </card>
  <card>
    <side><![CDATA[ἀναβαίνω]]></side>
    <side><![CDATA[ἀναβήσομαι, ἀνέβην, ἀναβέβηκα]]></side>
    <side><![CDATA[to go up]]></side>
  </card>
  <card>
    <side><![CDATA[ἀναγιγνώσκω]]></side>
    <side><![CDATA[ἀναγνώσομαι, ἀνέγνων, ἀνέγνωκα, ἀνέγνωσμαι, ἀνεγνώσθην]]></side>
    <side><![CDATA[to read]]></side>
  </card>
  <card>
    <side><![CDATA[ἀνάγκη ]]></side>
    <side><![CDATA[ἀνάγκης, ἡ]]></side>
    <side><![CDATA[force, constraint, necessity]]></side>
  </card>
  <card>
    <side><![CDATA[ἀναιρέω]]></side>
    <side><![CDATA[ἀναιρήσω, ἀνεῖλον, ἀνῄρηκα, ἀνῄρεμαι, ἀνῃρέθην]]></side>
    <side><![CDATA[to destroy; (mid) take up, pick up, choose]]></side>
  </card>
  <card>
    <side><![CDATA[ἀνδρεῖος -α -ον]]></side>
    <side><![CDATA[manly, brave]]></side>
  </card>
  <card>
    <side><![CDATA[ἄνεμος]]></side>
    <side><![CDATA[ανέμου, ὁ]]></side>
    <side><![CDATA[wind]]></side>
  </card>
  <card>
    <side><![CDATA[ἄνευ]]></side>
    <side><![CDATA[(gen) without]]></side>
  </card>
  <card>
    <side><![CDATA[ἀνήρ]]></side>
    <side><![CDATA[ἀνδρός, ὁ]]></side>
    <side><![CDATA[man, husband]]></side>
  </card>
  <card>
    <side><![CDATA[ἄνθρωπος]]></side>
    <side><![CDATA[ἀνθρώπου, ὁ, ἡ]]></side>
    <side><![CDATA[man, woman, human being, (pl.) people]]></side>
  </card>
  <card>
    <side><![CDATA[ἀντί]]></side>
    <side><![CDATA[(gen) instead of, in place of, ahead of, in return for]]></side>
  </card>
  <card>
    <side><![CDATA[ἄνω]]></side>
    <side><![CDATA[above, up]]></side>
  </card>
  <card>
    <side><![CDATA[ἄξιος -α -ον]]></side>
    <side><![CDATA[worthy of]]></side>
  </card>
  <card>
    <side><![CDATA[ἀπάγω]]></side>
    <side><![CDATA[ἀπάξω, ἀπήγαγον, ἀπῆχα, ἀπῆγμαι, ἀπήχθην]]></side>
    <side><![CDATA[to lead away]]></side>
  </card>
  <card>
    <side><![CDATA[ἄπειμι]]></side>
    <side><![CDATA[ἀπέσομαι, ἀπῆν]]></side>
    <side><![CDATA[to be away, be absent]]></side>
  </card>
  <card>
    <side><![CDATA[ἄπειμι]]></side>
    <side><![CDATA[to go away]]></side>
  </card>
  <card>
    <side><![CDATA[ἀπέρχομαι]]></side>
    <side><![CDATA[ἀπελεύσομαι, ἀπῆλθον (ἀπήλυθον), ἀπελήλυθα]]></side>
    <side><![CDATA[to go away, come away]]></side>
  </card>
  <card>
    <side><![CDATA[ἀπό]]></side>
    <side><![CDATA[(gen) away from]]></side>
  </card>
  <card>
    <side><![CDATA[ἀποβαίνω]]></side>
    <side><![CDATA[ἀποβήσομαι, ἀπέβην, ἀποβέβηκα]]></side>
    <side><![CDATA[to go away]]></side>
  </card>
  <card>
    <side><![CDATA[ἀποβάλλω]]></side>
    <side><![CDATA[ἀποβαλῶ, ἀπέβαλον, ἀποβέβληκα, ἀποβέβλημαι, ἀπεβλήθην]]></side>
    <side><![CDATA[to throw away]]></side>
  </card>
  <card>
    <side><![CDATA[ἀποδίδωμι]]></side>
    <side><![CDATA[ἀποδώσω, ἀπέδωκα, ἀποδέδωκα, ἀποδέδομαι, ἀπεδόθην]]></side>
    <side><![CDATA[to give back, return, pay, sell]]></side>
  </card>
  <card>
    <side><![CDATA[ἀποθνήσκω]]></side>
    <side><![CDATA[ἀποθανοῦμαι, ἀπέθανον, ἀποτέθνηκα]]></side>
    <side><![CDATA[to die, be put to death]]></side>
  </card>
  <card>
    <side><![CDATA[ἀποκρίνω]]></side>
    <side><![CDATA[ἀποκρινῶ, ἀπέκρινα, ἀποκέκρινα, ἀποκέκριμαι, ἀποκρίνθην]]></side>
    <side><![CDATA[(act) to separate; (mid) reply]]></side>
  </card>
  <card>
    <side><![CDATA[ἀποκτείνω]]></side>
    <side><![CDATA[ἀποκτενῶ, ἀπέκτεινα (ἀπέκτανον), ἀπέκτονα]]></side>
    <side><![CDATA[to kill]]></side>
  </card>
  <card>
    <side><![CDATA[ἀπόλλυμι]]></side>
    <side><![CDATA[ἀπολῶ, ἀπώλεσα, ἀπολώλεκα, ἀπόλωλα, ἀπωλόμην]]></side>
    <side><![CDATA[to destroy]]></side>
  </card>
  <card>
    <side><![CDATA[ἀποπλέω]]></side>
    <side><![CDATA[ἀποπλεύσομαι, ἀπέπλευσα,  ἀποπέπλευκα, ἀποπέπλευσμαι, ἀπεπλεύσθην]]></side>
